name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: 'NPM Install'
      run: npm install
    - name: 'NPM Build'
      run: npm run build
    - name: 'Cypress Run'
      uses: cypress-io/github-action@v2
      with:
        start: npm start
        wait-on: 'http://localhost:8080'
        wait-on-timeout: 120
    - name: 'Upload Cypress Screenshots'
      uses: actions/upload-artifact@v1
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots
    - name: 'Upload Cypress Videos'
      uses: actions/upload-artifact@v1
      if: always()
      with:
        name: cypress-videos
        path: cypress/videos
    - name: 'Copy RSS Feed'
      run: |
        mkdir dist/feed
        cp dist/rss.xml dist/feed/index.xml
    - name: 'Deploy'
      if: github.event_name != 'pull_request'
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/RehanSaeed/rehansaeed.github.io.git
        npx gh-pages --branch release --dist dist --user "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: 'Ping Sitemap to Google'
      run: curl http://www.google.com/ping?sitemap=https://rehansaeed.com/sitemap.xml
    - name: 'Ping Sitemap to Bing'
      run: curl http://www.bing.com/ping?sitemap=https://rehansaeed.com/sitemap.xml
    - name: 'Send Outgoing Webmentions'
      run: npx webmention https://rehansaeed.com/rss.xml --limit 10 --send
