name: Build

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        lfs: true
    - name: 'NPM Install'
      run: npm install
    - name: 'NPM Build'
      run: npm run build
    - name: 'Deploy'
      if: github.event_name != 'pull_request'
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/RehanSaeed/rehansaeed.github.io.git
        npx gh-pages --branch master --dist dist --user "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: 'Ping Sitemap to Google'
      run: curl http://www.google.com/ping?sitemap=https://rehansaeed.com/sitemap.xml
    - name: 'Ping Sitemap to Bing'
      run: curl http://www.bing.com/ping?sitemap=https://rehansaeed.com/sitemap.xml
