name: Build

concurrency: ${{ github.ref }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          lfs: true
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: "16"
          cache: npm
      - name: "NPM Install"
        run: npm ci
      - name: "NPM Build"
        run: npm run build
      - name: "Copy RSS Feed"
        run: |
          mkdir dist/feed
          cp dist/rss.xml dist/feed/index.xml
      - name: "Cypress Run"
        uses: cypress-io/github-action@v6.1.0
        with:
          start: npm start
          wait-on: "http://localhost:8080"
          wait-on-timeout: 120
      - name: "Upload Cypress Screenshots"
        uses: actions/upload-artifact@v3.1.2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: "Upload Cypress Videos"
        uses: actions/upload-artifact@v3.1.2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
      - name: "Deploy"
        if: github.event_name != 'pull_request'
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/RehanSaeed/rehansaeed.github.io.git
          npx gh-pages --branch release --dist dist --user "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "Ping Sitemap to Google"
        if: github.event_name != 'pull_request'
        run: curl http://www.google.com/ping?sitemap=https://rehansaeed.com/sitemap.xml
      - name: "Ping Sitemap to Bing"
        if: github.event_name != 'pull_request'
        run: curl http://www.bing.com/ping?sitemap=https://rehansaeed.com/sitemap.xml
      - name: "Send Outgoing Webmentions"
        if: github.event_name != 'pull_request'
        run: npx webmention https://rehansaeed.com/rss.xml --limit 10 --send
